---
app_name: "business-app"
app_user: "appuser"
app_group: "appuser"
app_dir: "/opt/{{ app_name }}"
app_port: 5000

keycloak_url: "http://192.168.56.10:8080"
keycloak_realm: "zerotrust"
keycloak_client_id: "business-app"
keycloak_client_secret: "ruIG7GbPczfU5tglMPtUMysKuJaekzKV"  

python_version: "3.8"