---
- name: Deploy systemd service
  template:
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
    mode: '0644'

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start Keycloak
  service:
    name: keycloak
    state: started
    enabled: yes
