---
wazuh_manager_version: "4.7.2"
wazuh_indexer_version: "4.7.2"
wazuh_dashboard_version: "4.7.2"

wazuh_manager_port: 1514
wazuh_api_port: 55000
wazuh_indexer_port: 9200
wazuh_dashboard_port: 443

# Heap size pour Indexer (optimis√© pour 2GB RAM)
indexer_heap_size: "512m"

# Admin credentials
wazuh_api_user: "wazuh"
wazuh_api_password: "wazuh123"
admin_password: "admin123"
