---
- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart oauth2-proxy
  service:
    name: oauth2-proxy
    state: restarted

- name: restart wireguard
  systemd:
    name: wg-quick@wg0
    state: restarted
